# -*- Mode: Makefile; indent-tabs-mode:t; tab-width: 4 -*-

all:

install:
	mkdir -p $(DESTDIR)/bin
	cp -a hello.py $(DESTDIR)/bin/create
	cp -a _find_fuse_parts.py $(DESTDIR)/bin
	chmod a+x $(DESTDIR)/bin/create
