#!/bin/sh

set -ex

# required for the debian adt host
mkdir -p /etc/systemd/system/snapd.service.d/
if [ "$http_proxy" != "" ]; then
    cat <<EOF | tee /etc/systemd/system/snapd.service.d/proxy.conf
[Service]
Environment=http_proxy=$http_proxy
Environment=https_proxy=$http_proxy
EOF

    # ensure environment is updated
    echo "http_proxy=$http_proxy" >> /etc/environment
    echo "https_proxy=$http_proxy" >> /etc/environment
fi
systemctl daemon-reload

# ensure we can do a connect to localhost
echo ubuntu:ubuntu|chpasswd
sed -i 's/\(PermitRootLogin\|PasswordAuthentication\)\>.*/\1 yes/' /etc/ssh/sshd_config
systemctl reload sshd.service

# If snapd's package has a release version (not built from git) then install core from candidate in the tests.
# This is intended to cope with the autopkgtest execution using the package from -proposed
if [ -z "$(apt list snapd | grep git)" ]; then
    export SPREAD_CORE_CHANNEL=candidate
fi

# and now run spread against localhost
. /etc/os-release
export GOPATH=/tmp/go
go get -u github.com/snapcore/spread/cmd/spread
/tmp/go/bin/spread -v autopkgtest:${ID}-${VERSION_ID}-$(dpkg --print-architecture)
